"""add asset entity ai queue and report models

Revision ID: 6be1956192ed
Revises: 
Create Date: 2026-06-28 10:16:41.616292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6be1956192ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_company_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('articles_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_report_asset_created', 'ai_company_reports', ['asset_id', 'created_at'], unique=False)
    op.create_index('idx_company_report_confidence', 'ai_company_reports', ['confidence_score'], unique=False)
    op.create_index('idx_company_report_sentiment', 'ai_company_reports', ['overall_sentiment'], unique=False)
    op.create_index(op.f('ix_ai_company_reports_asset_id'), 'ai_company_reports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ai_company_reports_ticker'), 'ai_company_reports', ['ticker'], unique=False)
    op.create_table('ai_job_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False, comment='article_summary | company_report | sector_report | market_report | embedding'),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment="'article' | 'asset' | 'sector' | 'market'"),
    sa.Column('priority', sa.Integer(), server_default='10', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment="'pending' | 'processing' | 'completed' | 'failed'"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_job_queue_job_type', 'ai_job_queue', ['job_type'], unique=False)
    op.create_index('idx_ai_job_queue_scheduled', 'ai_job_queue', ['scheduled_for'], unique=False)
    op.create_index('idx_ai_job_queue_status_priority', 'ai_job_queue', ['status', 'priority'], unique=False)
    op.create_index('idx_ai_job_queue_target', 'ai_job_queue', ['target_type', 'target_id'], unique=False)
    op.create_table('ai_market_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_report_date', 'ai_market_reports', ['report_date'], unique=False)
    op.create_table('ai_sector_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('assets_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_report_seCTOR_created', 'ai_sector_reports', ['sector', 'created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), server_default='stock', nullable=False, comment='stock | etf | crypto | index | commodity'),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('primary_ticker', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('raw_source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_ticker'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_assets_primary_ticker', 'assets', ['primary_ticker'], unique=False)
    op.create_index('idx_assets_sector', 'assets', ['sector'], unique=False)
    op.create_index('idx_assets_slug', 'assets', ['slug'], unique=False)
    op.create_index('idx_assets_type', 'assets', ['asset_type'], unique=False)
    op.create_table('asset_tickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('active_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'ticker', 'exchange', name='uq_asset_ticker_exchange')
    )
    op.create_index('idx_asset_tickers_lookup', 'asset_tickers', ['ticker'], unique=False)
    op.drop_index(op.f('idx_news_articles_ticker'), table_name='news_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_news_articles_ticker'), 'news_articles', ['ticker'], unique=False)
    op.drop_index('idx_asset_tickers_lookup', table_name='asset_tickers')
    op.drop_table('asset_tickers')
    op.drop_index('idx_assets_type', table_name='assets')
    op.drop_index('idx_assets_slug', table_name='assets')
    op.drop_index('idx_assets_sector', table_name='assets')
    op.drop_index('idx_assets_primary_ticker', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_sector_report_seCTOR_created', table_name='ai_sector_reports')
    op.drop_table('ai_sector_reports')
    op.drop_index('idx_market_report_date', table_name='ai_market_reports')
    op.drop_table('ai_market_reports')
    op.drop_index('idx_ai_job_queue_target', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_status_priority', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_scheduled', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_job_type', table_name='ai_job_queue')
    op.drop_table('ai_job_queue')
    op.drop_index(op.f('ix_ai_company_reports_ticker'), table_name='ai_company_reports')
    op.drop_index(op.f('ix_ai_company_reports_asset_id'), table_name='ai_company_reports')
    op.drop_index('idx_company_report_sentiment', table_name='ai_company_reports')
    op.drop_index('idx_company_report_confidence', table_name='ai_company_reports')
    op.drop_index('idx_company_report_asset_created', table_name='ai_company_reports')
    op.drop_table('ai_company_reports')
    # ### end Alembic commands ###
