"""add asset entity ai queue and report models

Revision ID: 6be1956192ed
Revises: 
Create Date: 2026-06-28 10:16:41.616292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6be1956192ed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS news_articles (
            id BIGSERIAL PRIMARY KEY,
            finnhub_id TEXT UNIQUE,
            ticker TEXT,
            title TEXT,
            summary TEXT,
            provider_name TEXT,
            article_url TEXT UNIQUE,
            thumbnail_url TEXT,
            pub_date TIMESTAMP WITHOUT TIME ZONE,
            raw_json JSONB,
            imported_at TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
        )
    """)
    op.execute("""
        DO $$
        DECLARE
            mismatch TEXT;
        BEGIN
            SELECT string_agg(expected.name, ', ' ORDER BY expected.name)
              INTO mismatch
              FROM (
                    VALUES
                        ('id', 'bigint', 'NO', NULL),
                        ('finnhub_id', 'text', 'YES', NULL),
                        ('ticker', 'text', 'YES', NULL),
                        ('title', 'text', 'YES', NULL),
                        ('summary', 'text', 'YES', NULL),
                        ('provider_name', 'text', 'YES', NULL),
                        ('article_url', 'text', 'YES', NULL),
                        ('thumbnail_url', 'text', 'YES', NULL),
                        ('pub_date', 'timestamp without time zone', 'YES', NULL),
                        ('raw_json', 'jsonb', 'YES', NULL),
                        ('imported_at', 'timestamp without time zone', 'NO', 'now()')
                   ) AS expected(name, data_type, is_nullable, column_default)
              LEFT JOIN information_schema.columns actual
                ON actual.table_schema = 'public'
               AND actual.table_name = 'news_articles'
               AND actual.column_name = expected.name
             WHERE actual.column_name IS NULL
                OR actual.data_type <> expected.data_type
                OR actual.is_nullable <> expected.is_nullable
                OR (
                    expected.column_default IS NOT NULL
                    AND actual.column_default IS DISTINCT FROM expected.column_default
                );

            IF mismatch IS NOT NULL THEN
                RAISE EXCEPTION
                    'Incompatible preexisting public.news_articles columns: %', mismatch;
            END IF;

            IF NOT EXISTS (
                SELECT 1
                  FROM pg_constraint c
                  JOIN pg_class t ON t.oid = c.conrelid
                  JOIN pg_namespace n ON n.oid = t.relnamespace
                 WHERE n.nspname = 'public'
                   AND t.relname = 'news_articles'
                   AND c.contype = 'p'
                   AND pg_get_constraintdef(c.oid) = 'PRIMARY KEY (id)'
            ) THEN
                RAISE EXCEPTION
                    'Incompatible preexisting public.news_articles: required PRIMARY KEY (id) is missing';
            END IF;

            IF NOT EXISTS (
                SELECT 1 FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = 'public' AND t.relname = 'news_articles'
                  AND c.contype = 'u'
                  AND pg_get_constraintdef(c.oid) = 'UNIQUE (finnhub_id)'
            ) OR NOT EXISTS (
                SELECT 1 FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = 'public' AND t.relname = 'news_articles'
                  AND c.contype = 'u'
                  AND pg_get_constraintdef(c.oid) = 'UNIQUE (article_url)'
            ) THEN
                RAISE EXCEPTION
                    'Incompatible preexisting public.news_articles: required unique constraints are missing';
            END IF;
        END
        $$
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_pub_date ON news_articles (pub_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_ticker_pub_date ON news_articles (ticker, pub_date)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_news_articles_imported_at ON news_articles (imported_at)")
    op.create_table('ai_company_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('articles_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('price_snapshot', sa.Float(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_company_report_asset_created', 'ai_company_reports', ['asset_id', 'created_at'], unique=False)
    op.create_index('idx_company_report_confidence', 'ai_company_reports', ['confidence_score'], unique=False)
    op.create_index('idx_company_report_sentiment', 'ai_company_reports', ['overall_sentiment'], unique=False)
    op.create_index(op.f('ix_ai_company_reports_asset_id'), 'ai_company_reports', ['asset_id'], unique=False)
    op.create_index(op.f('ix_ai_company_reports_ticker'), 'ai_company_reports', ['ticker'], unique=False)
    op.create_table('ai_job_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_type', sa.String(length=30), nullable=False, comment='article_summary | company_report | sector_report | market_report | embedding'),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False, comment="'article' | 'asset' | 'sector' | 'market'"),
    sa.Column('priority', sa.Integer(), server_default='10', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment="'pending' | 'processing' | 'completed' | 'failed'"),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='3', nullable=False),
    sa.Column('scheduled_for', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_job_queue_job_type', 'ai_job_queue', ['job_type'], unique=False)
    op.create_index('idx_ai_job_queue_scheduled', 'ai_job_queue', ['scheduled_for'], unique=False)
    op.create_index('idx_ai_job_queue_status_priority', 'ai_job_queue', ['status', 'priority'], unique=False)
    op.create_index('idx_ai_job_queue_target', 'ai_job_queue', ['target_type', 'target_id'], unique=False)
    op.create_table('ai_market_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_date', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), server_default='neutral', nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_market_report_date', 'ai_market_reports', ['report_date'], unique=False)
    op.create_table('ai_sector_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('report_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=20), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('assets_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('model_used', sa.String(length=50), server_default='', nullable=False),
    sa.Column('prompt_version', sa.String(length=20), server_default='1.0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_report_seCTOR_created', 'ai_sector_reports', ['sector', 'created_at'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('asset_type', sa.String(length=20), server_default='stock', nullable=False, comment='stock | etf | crypto | index | commodity'),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=True),
    sa.Column('primary_ticker', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('raw_source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='TRUE', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('primary_ticker'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_assets_primary_ticker', 'assets', ['primary_ticker'], unique=False)
    op.create_index('idx_assets_sector', 'assets', ['sector'], unique=False)
    op.create_index('idx_assets_slug', 'assets', ['slug'], unique=False)
    op.create_index('idx_assets_type', 'assets', ['asset_type'], unique=False)
    op.create_table('asset_tickers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.BigInteger(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), server_default='FALSE', nullable=False),
    sa.Column('active_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('active_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'ticker', 'exchange', name='uq_asset_ticker_exchange')
    )
    op.create_index('idx_asset_tickers_lookup', 'asset_tickers', ['ticker'], unique=False)
    op.drop_index(op.f('idx_news_articles_ticker'), table_name='news_articles', if_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_news_articles_ticker'), 'news_articles', ['ticker'], unique=False)
    op.drop_index('idx_asset_tickers_lookup', table_name='asset_tickers')
    op.drop_table('asset_tickers')
    op.drop_index('idx_assets_type', table_name='assets')
    op.drop_index('idx_assets_slug', table_name='assets')
    op.drop_index('idx_assets_sector', table_name='assets')
    op.drop_index('idx_assets_primary_ticker', table_name='assets')
    op.drop_table('assets')
    op.drop_index('idx_sector_report_seCTOR_created', table_name='ai_sector_reports')
    op.drop_table('ai_sector_reports')
    op.drop_index('idx_market_report_date', table_name='ai_market_reports')
    op.drop_table('ai_market_reports')
    op.drop_index('idx_ai_job_queue_target', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_status_priority', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_scheduled', table_name='ai_job_queue')
    op.drop_index('idx_ai_job_queue_job_type', table_name='ai_job_queue')
    op.drop_table('ai_job_queue')
    op.drop_index(op.f('ix_ai_company_reports_ticker'), table_name='ai_company_reports')
    op.drop_index(op.f('ix_ai_company_reports_asset_id'), table_name='ai_company_reports')
    op.drop_index('idx_company_report_sentiment', table_name='ai_company_reports')
    op.drop_index('idx_company_report_confidence', table_name='ai_company_reports')
    op.drop_index('idx_company_report_asset_created', table_name='ai_company_reports')
    op.drop_table('ai_company_reports')
    # ### end Alembic commands ###
