"""
AI Report ORM Models — Persisted intelligence outputs at company, sector, and market levels.

These tables store the permanent, cached outputs of AI enrichment so page requests
never trigger expensive LLM calls. Reports are regenerated asynchronously via the
event-driven pipeline only when their input data changes.
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import BigInteger, ForeignKey, Integer, String, Text, Float, func, Index
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.config.database import Base


class AICompanyReport(Base):
    """Per-asset (company) intelligence report generated by Ollama."""
    __tablename__ = "ai_company_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)

    # FK to asset (not ticker string)
    asset_id: Mapped[int] = mapped_column(BigInteger, ForeignKey("assets.id"), nullable=False, index=True)

    # Denormalized ticker for quick lookups
    ticker: Mapped[str] = mapped_column(Text, nullable=False, index=True)

    # Report payload
    report_data: Mapped[dict] = mapped_column(JSONB, nullable=False)

    # Denormalized query columns (avoids JSONB ops for filtering/sorting)
    overall_sentiment: Mapped[str] = mapped_column(String(20), nullable=False)
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)
    articles_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")

    # Model tracking
    model_used: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    prompt_version: Mapped[str] = mapped_column(String(20), nullable=False, server_default="1.0")

    # Price snapshot at analysis time
    price_snapshot: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP, server_default=func.now(), onupdate=func.now()
    )

    # One report per asset at a time (latest wins; old rows pruned)
    asset = relationship("Asset", back_populates="company_reports")

    __table_args__ = (
        Index("idx_company_report_asset_created", "asset_id", "created_at"),
        Index("idx_company_report_sentiment", "overall_sentiment"),
        Index("idx_company_report_confidence", "confidence_score"),
    )

    def __repr__(self):
        return f"<AICompanyReport asset_id={self.asset_id} ticker={self.ticker} sentiment={self.overall_sentiment}>"


class AISectorReport(Base):
    """Aggregated sector intelligence report."""
    __tablename__ = "ai_sector_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    sector: Mapped[str] = mapped_column(String(100), nullable=False)
    report_data: Mapped[dict] = mapped_column(JSONB, nullable=False)
    overall_sentiment: Mapped[str] = mapped_column(String(20), nullable=False)
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)
    assets_count: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    model_used: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    prompt_version: Mapped[str] = mapped_column(String(20), nullable=False, server_default="1.0")
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())

    __table_args__ = (
        Index("idx_sector_report_seCTOR_created", "sector", "created_at"),
    )

    def __repr__(self):
        return f"<AISectorReport sector={self.sector} sentiment={self.overall_sentiment}>"


class AIMarketReport(Base):
    """Daily market-wide intelligence report."""
    __tablename__ = "ai_market_reports"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    report_date: Mapped[datetime] = mapped_column(TIMESTAMP, nullable=False)
    report_data: Mapped[dict] = mapped_column(JSONB, nullable=False)
    overall_sentiment: Mapped[str] = mapped_column(String(20), nullable=False)
    risk_level: Mapped[str] = mapped_column(String(20), nullable=False, server_default="neutral")
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)
    model_used: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    prompt_version: Mapped[str] = mapped_column(String(20), nullable=False, server_default="1.0")
    created_at: Mapped[datetime] = mapped_column(TIMESTAMP, server_default=func.now())

    __table_args__ = (
        Index("idx_market_report_date", "report_date"),
    )

    def __repr__(self):
        return f"<AIMarketReport date={self.report_date} sentiment={self.overall_sentiment}>"
