"""Analysis Report ORM Model

Persisted financial analysis reports generated by Ollama.
Denormalized columns enable efficient filtering without JSONB queries.
"""

from sqlalchemy import BigInteger, Integer, String, Text, Float, func, Index, desc
from sqlalchemy.dialects.postgresql import JSONB, TIMESTAMP
from sqlalchemy.orm import Mapped, mapped_column

from backend.config.database import Base


class AnalysisReportModel(Base):
    __tablename__ = "analysis_reports"

    id: Mapped[int] = mapped_column(
        BigInteger, primary_key=True, autoincrement=True
    )

    ticker: Mapped[str] = mapped_column(Text, nullable=False)

    report_data: Mapped[object] = mapped_column(JSONB, nullable=False)

    # Denormalized columns for efficient filtering/sorting without JSONB ops
    overall_sentiment: Mapped[str] = mapped_column(String(20), nullable=False)
    confidence_score: Mapped[int] = mapped_column(Integer, nullable=False)
    articles_count: Mapped[int] = mapped_column(Integer, nullable=False)
    model_used: Mapped[str] = mapped_column(String(50), nullable=False, server_default="")
    prompt_version: Mapped[str] = mapped_column(String(20), nullable=False, server_default="1.0")
    current_price_at_analysis: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[object] = mapped_column(TIMESTAMP, server_default=func.now())

    __table_args__ = (
        Index("idx_reports_ticker", "ticker"),
        Index("idx_reports_created", desc("created_at")),
        Index("idx_reports_ticker_created", "ticker", desc("created_at")),
    )
